// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYczBllQnW69EN_Cm9IHPk3bp6sAEOy4',
    appId: '1:463665400019:web:47e26171841e822bbb6c26',
    messagingSenderId: '463665400019',
    projectId: 'todo-cf7ba',
    authDomain: 'todo-cf7ba.firebaseapp.com',
    storageBucket: 'todo-cf7ba.firebasestorage.app',
    measurementId: 'G-7WLLPDPS33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_tqEmPLLNVHkeb0VTafJyLly-wVIbjqo',
    appId: '1:463665400019:android:fe8c7d591e07c90fbb6c26',
    messagingSenderId: '463665400019',
    projectId: 'todo-cf7ba',
    storageBucket: 'todo-cf7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTIxcxSzWIMa6_XT16RC2dMJuzQA4A9Y',
    appId: '1:463665400019:ios:8d5033b2b19f9da3bb6c26',
    messagingSenderId: '463665400019',
    projectId: 'todo-cf7ba',
    storageBucket: 'todo-cf7ba.firebasestorage.app',
    iosBundleId: 'com.example.taskManageMent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqTIxcxSzWIMa6_XT16RC2dMJuzQA4A9Y',
    appId: '1:463665400019:ios:8d5033b2b19f9da3bb6c26',
    messagingSenderId: '463665400019',
    projectId: 'todo-cf7ba',
    storageBucket: 'todo-cf7ba.firebasestorage.app',
    iosBundleId: 'com.example.taskManageMent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYczBllQnW69EN_Cm9IHPk3bp6sAEOy4',
    appId: '1:463665400019:web:47e26171841e822bbb6c26',
    messagingSenderId: '463665400019',
    projectId: 'todo-cf7ba',
    authDomain: 'todo-cf7ba.firebaseapp.com',
    storageBucket: 'todo-cf7ba.firebasestorage.app',
    measurementId: 'G-7WLLPDPS33',
  );

}